#ifndef __WIFI_HTTP_BOARD_H
#define __WIFI_HTTP_BOARD_H

#define BAUD_RATE  19200
#define WIFI_SVR_BEGIN_INTMS  250
#define WIFI_SVR_POLLING_INTMS  500
#define WIFI_CLI_BEGIN_INTMS  250
#define WIFI_CLI_POLLING_INTMS  500

#define WIFI_URL_QUERY "/query/"

#define GPIO_HIGH 1
#define GPIO_LOW 0

#define PIN_LED_HCHECK 2
#define PIN_LED_CONNECTING 4
#define PIN_LED_SVRCLI 5
#define PIN_SVRCLI_MODE 16

#define PIN_SWSERIAL_RX 14
#define PIN_SWSERIAL_TX 12
#define PIN_SWSERIAL_GND 13

#endif // __WIFI_HTTP_BOARD_H
